In [3]:
import numpy as np

### Basic Operations with Scalars

In [10]:
nums = np.arange(0,10)
print(nums)

print(nums + 3)
print(nums - 3)
print(nums * 3)
print(nums / 3)
print(nums // 3)
print(nums ** 2)
print(nums % 2)

print(nums > 4)
print(nums < 7)

[0 1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10 11 12]
[-3 -2 -1  0  1  2  3  4  5  6]
[ 0  3  6  9 12 15 18 21 24 27]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]
[0 0 0 1 1 1 2 2 2 3]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]
[False False False False False  True  True  True  True  True]
[ True  True  True  True  True  True  True False False False]


### Basic Operations Between Arrays

In [11]:
nums = np.arange(0,10)
print(nums)

nums2 = np.arange(10,20)
print(nums2)

print(nums + nums2)
print(nums - nums2)
print(nums * nums2)
print(nums / nums2)
print(nums // nums2)
print(nums ** nums2)
print(nums % nums2)

print(nums > nums2)
print(nums < nums2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[  0  11  24  39  56  75  96 119 144 171]
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]
[0 0 0 0 0 0 0 0 0 0]
[          0           1        4096     1594323   268435456   452807053
  -683606016 -2094633337           0  -400556711]
[0 1 2 3 4 5 6 7 8 9]
[False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True]


### Dot Product

In [6]:
nums = np.array([1,2,3])
print(nums)

nums2 = np.array([3,4,5])
print(nums2)

print(nums.dot(nums2))

nums = np.array([
    [1,2,3], 
    [4,5,6]
])
print(nums)

nums2 = np.array([
    [7,8],
    [9,0],
    [1,2]
])
print(nums2)

nums.dot(nums2)

[1 2 3]
[3 4 5]
26
[[1 2 3]
 [4 5 6]]
[[7 8]
 [9 0]
 [1 2]]


array([[28, 14],
       [79, 44]])

### Basic Array Analysis

In [17]:
nums = np.array([
    [1,2,3], 
    [4,5,6]
])
print(nums)

print(nums.min(axis=1))
print(nums.max(axis=0))
print(nums.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[1 4]
[3 6]
[ 6 15]
