In [1]:
import numpy as np

### Indexing and Slicing

In [5]:
nums = np.array([3,2,6,4,1,8,9,5,6,1])

print(nums)

print(nums[1])

print(nums[3:])
print(nums[:3])
print(nums[3:6])
print(nums[:])
print(nums[-2])
print(nums[::2])
print(nums[1::2])
print(nums[::-1])

[3 2 6 4 1 8 9 5 6 1]
2
[4 1 8 9 5 6 1]
[3 2 6]
[4 1 8]
[3 2 6 4 1 8 9 5 6 1]
6
[3 6 1 9 6]
[2 4 8 5 1]


### Iterate

In [9]:
nums = np.random.randint(1,100, size = 100)

for num in nums:
    print(num)

38
25
34
74
42
47
86
72
84
70
67
43
42
21
91
85
14
88
57
31
83
98
80
22
10
30
33
10
83
78
1
4
21
39
4
99
37
7
59
36
55
27
12
98
15
67
8
70
1
15
57
97
13
25
43
80
62
26
35
74
83
89
72
99
79
49
22
49
97
18
2
73
97
4
35
74
7
23
19
95
86
24
54
61
50
32
15
26
16
63
42
65
46
83
59
48
83
53
81
12


In [11]:
nums = np.array([
    [1,2,3,4,5],
    [5,4,3,2,1],
    [9,8,6,5,3]
])

for index, num in np.ndenumerate(nums):
    print(index, num)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 5
(1, 1) 4
(1, 2) 3
(1, 3) 2
(1, 4) 1
(2, 0) 9
(2, 1) 8
(2, 2) 6
(2, 3) 5
(2, 4) 3
